# Generated by Django 5.2 on 2025-05-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_categoria_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='imagen',
            field=models.ImageField(upload_to='dispositivos/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='usuarios/ironman.jpg', upload_to='usuarios/'),
        ),
    ]
